### ISSUE TITLE
getting exception details

### ISSUE THREAD

**Issue by AnassKartit** [OfficeDev/PnP-Partner-Pack#109]
Hi,
how can I find which field/list occured for the message below?

[04/27/2016 15:11:48 > 2631d4: INFO] 06/09 - List instances
[04/27/2016 15:12:58 > 2631d4: INFO] Exception occurred: Value does not fall within the expected range.
[04/27/2016 15:12:58 > 2631d4: INFO] Stack Trace:
[04/27/2016 15:12:58 > 2631d4: INFO]    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
[04/27/2016 15:12:58 > 2631d4: INFO]    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
[04/27/2016 15:12:58 > 2631d4: INFO]    at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
[04/27/2016 15:12:58 > 2631d4: INFO]    at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
[04/27/2016 15:12:58 > 2631d4: INFO]    at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
[04/27/2016 15:12:58 > 2631d4: INFO]    at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
[04/27/2016 15:12:58 > 2631d4: INFO]    at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
[04/27/2016 15:12:58 > 2631d4: INFO]    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.CreateFieldRef(ListInfo listInfo, Field field, FieldRef fieldRef)
[04/27/2016 15:12:58 > 2631d4: INFO]    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectListInstance.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
[04/27/2016 15:12:58 > 2631d4: INFO]    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
[04/27/2016 15:12:58 > 2631d4: INFO]    at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
[04/27/2016 15:12:58 > 2631d4: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.CreateSiteCollection(SiteCollectionProvisioningJob job)
[04/27/2016 15:12:58 > 2631d4: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.RunJobInternal(ProvisioningJob job)
[04/27/2016 15:12:58 > 2631d4: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.ProvisioningJobHandler.RunJob(ProvisioningJob job)

**Comment by PaoloPia** [comment]
Hi,
Unfortunately we don't have deep diagnostics in the job for such kind of issues. However, you can execute the job in VS2015 and debug it.

**Comment by PaoloPia** [comment]
Hi,
have you found the issues? Can we close this item? Thanks.

**Comment by PaoloPia** [comment]
Hi,
I will close this item, becase I don't see any feedback since many days ago. Feel free to open it again in case of need. Thanks.
