### ISSUE TITLE
Error in Website

### ISSUE THREAD

**Issue by SnappyFPV** [OfficeDev/PnP-Partner-Pack#126]
Hi perhaps someone give me a hint whats going wrong - when i opening the web app i get error ... only thing i found in log is:

The CodeDom provider type "Microsoft.CodeDom.Providers.DotNetCompilerPlatform.CSharpCodeProvider, Microsoft.CodeDom.Providers.DotNetCompilerPlatform, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" could not be located. (D:\home\site\wwwroot\web.config line 148)
   at System.CodeDom.Compiler.CompilerInfo.get_CodeDomProviderType()
   at System.Web.Configuration.CompilationSection.GetCompilerInfoFromLanguage(String language)
   at System.Web.UI.TemplateParser.ProcessLanguageAttribute(String language)
   at System.Web.UI.TemplateParser.ProcessMainDirectiveAttribute(String deviceName, String name, String value, IDictionary parseData)
   at System.Web.UI.TemplateParser.ProcessMainDirective(IDictionary mainDirective)

Did i miss something in tutorial?

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. Does the solution build in VS2015?

**Comment by PaoloPia** [comment]
Hi,
Any news about this topic? Otherwise, I will close the issue. Thanks.

**Comment by PaoloPia** [comment]
I will close this one for lack of response. I assume it is ok, otherwise let me know and I will be more than welcome to re-open it. Thanks.
