### ISSUE TITLE
ContinousWebJob Pending Restart

### ISSUE THREAD

**Issue by amirkhanRC** [OfficeDev/PnP-Partner-Pack#128]
Hi there,

I've published the 2 azure web jobs as suggested in your video and tried creating a site collections which is stuck on pending.

The continous webjob status is pending restart and the logging suggests to run an exe:
[07/10/2016 16:57:16 > 65012a: SYS ERR ] Job failed due to exit code -532462766
[07/10/2016 16:57:16 > 65012a: SYS INFO] Process went down, waiting for 60 seconds
[07/10/2016 16:57:16 > 65012a: SYS INFO] Status changed to PendingRestart
[07/10/2016 16:58:16 > 65012a: SYS INFO] Run script 'OfficeDevPnP.PartnerPack.ContinousJob.exe' with script host - 'WindowsScriptHost'
[07/10/2016 16:58:16 > 65012a: SYS INFO] Status changed to Running

However running this exe triggers and error stating that a storage account is not configured correctly:
Unhandled Exception: 
System.InvalidOperationException: Failed to validate Microsoft Azure WebJobs SDK Dashboard connection string. The Microsoft Azure 
Storage account connection string is not formatted correctly. Please visit 
http://msdn.microsoft.com/en-us/library/windowsazure/ee758697.aspx for details about configuring Microsoft Azure Storage connection 
strings.
   at Microsoft.Azure.WebJobs.Host.Executors.StorageAccountParser.ParseAccount(String connectionString, String connectionStringName, 
IServiceProvider services)
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider.get_DashboardAccount()
   at Microsoft.Azure.WebJobs.Host.Executors.DefaultStorageAccountProvider.<GetAccountAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<CreateAndLogHostStartedAsync>d__b.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.Host.Executors.JobHostContextFactory.<CreateAndLogHostStartedAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.<CreateContextAndLogHostStartedAsync>d__f.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.WebJobs.JobHost.Start()
   at Microsoft.Azure.WebJobs.JobHost.RunAndBlock()
   at OfficeDevPnP.PartnerPack.ContinousJob.Program.Main() in C:\Users\amirk\Downloads\PnP-Partner-Pack-master\OfficeDevPnP.PartnerPack.
SiteProvisioning\OfficeDevPnP.PartnerPack.ContinousJob\Program.cs:line 19

==================================================
I haven't created any storage accounts nor have I added any connection strings. Have I overlooked something?
(see attachments)
Thanks
Amir
![pnpwebjobs-pending](https://cloud.githubusercontent.com/assets/20151481/16714897/1672e47e-46d1-11e6-99d7-5d1dc464b576.PNG)
![pnpwebjobs-error](https://cloud.githubusercontent.com/assets/20151481/16714898/192aed92-46d1-11e6-9d90-65b8355b95c5.PNG)

**Comment by PaoloPia** [comment]
Hi,
Thanks for using the PnP Partner Pack. You have to configure a storage account that will be use to store the queued messages for the job. Please follow step by step the installation video (https://channel9.msdn.com/blogs/OfficeDevPnP/PnP-Partner-Pack-Setup-and-configuration) or the setup guidance (https://github.com/OfficeDev/PnP-Partner-Pack/blob/master/Documentation/Manual-Setup-Guide.md) for further details. Thanks.

**Comment by amirkhanRC** [comment]
Hi again Paolo. resolved the issue with the status of the webjobs. somehow the connectionstrings in the app.configs for AzureWebJobsDashboard & AzureWebJobsStorage had "&quot" appended to it. 
Issue must have occured when I provided params for Configure-Configs.ps1. maybe added quotes when I shouldn't?

So... Webjobs are running however, my site collection provisioning as well subsite provisioning jobs are  still pending for over 2 hours. 
in the webjobs dashboard I dont see any errors or activity for continousjob only following:
[07/12/2016 12:41:15 > 65012a: SYS INFO] Status changed to Running
[07/12/2016 12:41:18 > 65012a: INFO] Found the following functions:
[07/12/2016 12:41:18 > 65012a: INFO] OfficeDevPnP.PartnerPack.ContinousJob.Functions.ProcessQueueMessage
[07/12/2016 12:41:18 > 65012a: INFO] Job host started

any insights are greatly appreciated
amir

**Comment by PaoloPia** [comment]
Thanks for letting me know.
