### ISSUE TITLE
Timeouts when activating Composed Looks

### ISSUE THREAD

**Issue by kmees** [OfficeDev/PnP-Partner-Pack#140]
We're getting occasional timeouts during composed look activation when provisioning a new site collection. This happens roughly once every 5 provisionings. Is it possible to increase / customize the timeout somewhere? As a workaround, I wrote an ExtensibilityHandler that activates the composed look (and catches any errors / retries) and removed it from the template. That works but feels odd.

```
[08/12/2016 09:18:39 > 21e9b2: INFO] 08/10 - Composed Looks
[08/12/2016 09:21:43 > 21e9b2: INFO] Exception occurred: The operation has timed out
[08/12/2016 09:21:43 > 21e9b2: INFO] Stack Trace:
[08/12/2016 09:21:43 > 21e9b2: INFO]    at System.Net.HttpWebRequest.GetResponse()
[08/12/2016 09:21:43 > 21e9b2: INFO]    at Microsoft.SharePoint.Client.SPWebRequestExecutor.Execute()
[08/12/2016 09:21:43 > 21e9b2: INFO]    at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServer(ChunkStringBuilder sb)
[08/12/2016 09:21:43 > 21e9b2: INFO]    at Microsoft.SharePoint.Client.ClientRequest.ExecuteQuery()
[08/12/2016 09:21:43 > 21e9b2: INFO]    at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQuery()
[08/12/2016 09:21:43 > 21e9b2: INFO]    at Microsoft.SharePoint.Client.ClientContext.ExecuteQuery()
[08/12/2016 09:21:43 > 21e9b2: INFO]    at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay)
[08/12/2016 09:21:43 > 21e9b2: INFO]    at Microsoft.SharePoint.Client.BrandingExtensions.SetThemeByUrl(Web web, String paletteServerRelativeUrl, String fontServerRelativeUrl, String backgroundServerRelativeUrl, Boolean resetSubsitesToInherit, Boolean updateRootOnly)
[08/12/2016 09:21:43 > 21e9b2: INFO]    at Microsoft.SharePoint.Client.BrandingExtensions.SetComposedLookByUrl(Web web, String lookName, String paletteServerRelativeUrl, String fontServerRelativeUrl, String backgroundServerRelativeUrl, String masterServerRelativeUrl, Boolean resetSubsitesToInherit, Boolean updateRootOnly)
[08/12/2016 09:21:43 > 21e9b2: INFO]    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectComposedLook.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
[08/12/2016 09:21:43 > 21e9b2: INFO]    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
[08/12/2016 09:21:43 > 21e9b2: INFO]    at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
[08/12/2016 09:21:43 > 21e9b2: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.CreateSiteCollection(SiteCollectionProvisioningJob job)
[08/12/2016 09:21:43 > 21e9b2: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.RunJobInternal(ProvisioningJob job)
[08/12/2016 09:21:43 > 21e9b2: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.ProvisioningJobHandler.RunJob(ProvisioningJob job)
[08/12/2016 09:21:43 > 21e9b2: INFO] 
[08/12/2016 09:21:43 > 21e9b2: INFO] Ending job
```

Composed Look definition in Template:
```xml
<pnp:ComposedLook Name="Company Blue" ColorFile="{themecatalog}/15/comppany_blue.spcolor" FontFile="" BackgroundFile="" Version="0" />
```

**Comment by artokai** [comment]
I don't think the timeout value can be customized through any parameters, but you could try to change the code of ```SiteCollectionProvisioningJobHandler.cs``` to this:

```csharp
// Move to the context of the created Site Collection 
using (ClientContext clientContext = PnPPartnerPackContextProvider.GetAppOnlyClientContext(siteUrl)) 
{ 
   clientContext.RequestTimeout = Timeout.Infinite;
   Site site = clientContext.Site; 
   Web web = site.RootWeb; 
   ...
``` 

(The place where code needs changing is highlighted [here](https://github.com/OfficeDev/PnP-Partner-Pack/blob/c9b1aab789f9ed90538c0cb763c0521556d40e2e/OfficeDevPnP.PartnerPack.SiteProvisioning/OfficeDevPnP.PartnerPack.Infrastructure/Jobs/Handlers/SiteCollectionProvisioningJobHandler.cs#L91-L95))

Setting the timeout to inifinite has however some drawbacks. I've faced a situation where a webjob got stuck sometimes because it was waiting for an operation in SPOnline to complete which never happened... So I recommend using some finite (but large enough) timeout value instead.

**Comment by PaoloPia** [comment]
Hi,
I've fixed the implementation in the PnP Partner Pack v2 (which will be ready pretty soon). I will close this PR. Thanks for your contribution.
