### ISSUE TITLE
Bug v1.1: Composed Looks...

### ISSUE THREAD

**Issue by 2P2-Anthony** [OfficeDev/PnP-Partner-Pack#153]
Version 1.1

I've built a very basic template and whether I select include Composed Looks or not, the build of a site collection fails on the Composed Looks feature:

`[09/26/2016 23:52:30 > a87042: INFO] 09/12 - Custom Actions
[09/26/2016 23:52:30 > a87042: INFO] 10/12 - Composed Looks
[09/26/2016 23:52:32 > a87042: INFO] Exception occurred: Value cannot be null.
[09/26/2016 23:52:32 > a87042: INFO] Parameter name: masterPageServerRelativeUrl
[09/26/2016 23:52:32 > a87042: INFO] Stack Trace:
[09/26/2016 23:52:32 > a87042: INFO]    at Microsoft.SharePoint.Client.BrandingExtensions.SetMasterPageByUrl(Web web, String masterPageServerRelativeUrl, Boolean resetSubsitesToInherit, Boolean updateRootOnly)
[09/26/2016 23:52:32 > a87042: INFO]    at Microsoft.SharePoint.Client.BrandingExtensions.SetComposedLookByUrl(Web web, String lookName, String paletteServerRelativeUrl, String fontServerRelativeUrl, String backgroundServerRelativeUrl, String masterServerRelativeUrl, Boolean resetSubsitesToInherit, Boolean updateRootOnly)
[09/26/2016 23:52:32 > a87042: INFO]    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.ObjectComposedLook.ProvisionObjects(Web web, ProvisioningTemplate template, TokenParser parser, ProvisioningTemplateApplyingInformation applyingInformation)
[09/26/2016 23:52:32 > a87042: INFO]    at OfficeDevPnP.Core.Framework.Provisioning.ObjectHandlers.SiteToTemplateConversion.ApplyRemoteTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation provisioningInfo)
[09/26/2016 23:52:32 > a87042: INFO]    at Microsoft.SharePoint.Client.WebExtensions.ApplyProvisioningTemplate(Web web, ProvisioningTemplate template, ProvisioningTemplateApplyingInformation applyingInformation)
[09/26/2016 23:52:32 > a87042: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.CreateSiteCollection(SiteCollectionProvisioningJob job)
[09/26/2016 23:52:32 > a87042: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.SiteCollectionProvisioningJobHandler.RunJobInternal(ProvisioningJob job)
[09/26/2016 23:52:32 > a87042: INFO]    at OfficeDevPnP.PartnerPack.Infrastructure.Jobs.Handlers.ProvisioningJobHandler.RunJob(ProvisioningJob job)
[09/26/2016 23:52:32 > a87042: INFO] `

If I edit the template XML and remove the following line:

`<pnp:ComposedLook Name="" ColorFile="" FontFile="" BackgroundFile="" Version="0" />`

It successfully completes the Site Collection build.

If I have time to dig into the code, I'll see if I can find the bug. 

Is this bug fixed in v2.0?

**Comment by PaoloPia** [comment]
Hi,
I would suggest you to upgrade to the PnP Partner Pack v.2 or at least to upgrade the solution (v.1.1) to the latest release of the PnP Core Library. In fact, it could be to an issue we had in the engine some months ago.

**Comment by 2P2-Anthony** [comment]
I've already bumped my package code to v2.0, but if I revert I'll keep in mind that the core libraries should be updated to Sept 2016 or later.
